# Secure note types that contain account-like information
ALLOWED_SECURE_NOTE_TYPES = [
    b"Server",
    b"Email Account",
    b"SSH Key",
    b"Database",
    b"Stripe Key",
    b"Passport",
    b"Membership",
    b"Wi-Fi Password",
    b"Software License",
    b"Social Security",
    b"Address",
    b"Bank Account",
    b"Credit Card",
    b"Email Account",
    b"Health Insurance",
    b"Insurance",
    b"Instant Messenger",
    b"Generic",
    b"Custom",
]
